/* tslint:disable */
/* eslint-disable */
/**
 * letter_api API
 * letter_api API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LetterConfigModel,
} from '../models/index';
import {
    LetterConfigModelFromJSON,
    LetterConfigModelToJSON,
} from '../models/index';

export interface ApiV1InfoLogoOrgNameGetRequest {
    orgName: string;
}

export interface ApiV1LetterPostRequest {
    letterConfigModel: LetterConfigModel;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 
     */
    async apiV1HealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async apiV1HealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiV1HealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 
     */
    async apiV1InfoLogoOrgNameGetRaw(requestParameters: ApiV1InfoLogoOrgNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['orgName'] == null) {
            throw new runtime.RequiredError(
                'orgName',
                'Required parameter "orgName" was null or undefined when calling apiV1InfoLogoOrgNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/info/logo/{orgName}`.replace(`{${"orgName"}}`, encodeURIComponent(String(requestParameters['orgName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 
     */
    async apiV1InfoLogoOrgNameGet(requestParameters: ApiV1InfoLogoOrgNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiV1InfoLogoOrgNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     */
    async apiV1LetterPostRaw(requestParameters: ApiV1LetterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['letterConfigModel'] == null) {
            throw new runtime.RequiredError(
                'letterConfigModel',
                'Required parameter "letterConfigModel" was null or undefined when calling apiV1LetterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/letter`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LetterConfigModelToJSON(requestParameters['letterConfigModel']),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * 
     */
    async apiV1LetterPost(requestParameters: ApiV1LetterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiV1LetterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
