/* tslint:disable */
/* eslint-disable */
/**
 * letter_api API
 * letter_api API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankInformation
 */
export interface BankInformation {
    /**
     * 
     * @type {string}
     * @memberof BankInformation
     */
    orgName: string;
    /**
     * 
     * @type {string}
     * @memberof BankInformation
     */
    bankName: string;
    /**
     * 
     * @type {string}
     * @memberof BankInformation
     */
    iban: string;
}

/**
 * Check if a given object implements the BankInformation interface.
 */
export function instanceOfBankInformation(value: object): value is BankInformation {
    if (!('orgName' in value) || value['orgName'] === undefined) return false;
    if (!('bankName' in value) || value['bankName'] === undefined) return false;
    if (!('iban' in value) || value['iban'] === undefined) return false;
    return true;
}

export function BankInformationFromJSON(json: any): BankInformation {
    return BankInformationFromJSONTyped(json, false);
}

export function BankInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'orgName': json['orgName'],
        'bankName': json['bankName'],
        'iban': json['iban'],
    };
}

  export function BankInformationToJSON(json: any): BankInformation {
      return BankInformationToJSONTyped(json, false);
  }

  export function BankInformationToJSONTyped(value?: BankInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgName': value['orgName'],
        'bankName': value['bankName'],
        'iban': value['iban'],
    };
}

