/* tslint:disable */
/* eslint-disable */
/**
 * letter_api API
 * letter_api API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Vorstand } from './Vorstand';
import {
    VorstandFromJSON,
    VorstandFromJSONTyped,
    VorstandToJSON,
    VorstandToJSONTyped,
} from './Vorstand';
import type { BankInformation } from './BankInformation';
import {
    BankInformationFromJSON,
    BankInformationFromJSONTyped,
    BankInformationToJSON,
    BankInformationToJSONTyped,
} from './BankInformation';

/**
 * 
 * @export
 * @interface LetterConfigModel
 */
export interface LetterConfigModel {
    /**
     * 
     * @type {string}
     * @memberof LetterConfigModel
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof LetterConfigModel
     */
    content: string;
    /**
     * 
     * @type {boolean}
     * @memberof LetterConfigModel
     */
    includeSignUp: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LetterConfigModel
     */
    includeTableOfContents: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LetterConfigModel
     */
    signUpIncludeAbroadClause: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LetterConfigModel
     */
    includeFrontPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LetterConfigModel
     */
    includeHolidayLawPage: boolean;
    /**
     * 
     * @type {string}
     * @memberof LetterConfigModel
     */
    place: string;
    /**
     * 
     * @type {string}
     * @memberof LetterConfigModel
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof LetterConfigModel
     */
    organizationName: string;
    /**
     * 
     * @type {string}
     * @memberof LetterConfigModel
     */
    website?: string;
    /**
     * 
     * @type {Array<Vorstand>}
     * @memberof LetterConfigModel
     */
    people: Array<Vorstand>;
    /**
     * 
     * @type {BankInformation}
     * @memberof LetterConfigModel
     */
    bankInformation?: BankInformation;
    /**
     * 
     * @type {Date}
     * @memberof LetterConfigModel
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof LetterConfigModel
     */
    logo: LetterConfigModelLogoEnum;
}


/**
 * @export
 */
export const LetterConfigModelLogoEnum = {
    Dpsg: 'DPSG',
    Langenbach: 'Langenbach',
    Moosburg: 'Moosburg',
    Freising: 'Freising',
    BezirkFs: 'BezirkFS'
} as const;
export type LetterConfigModelLogoEnum = typeof LetterConfigModelLogoEnum[keyof typeof LetterConfigModelLogoEnum];


/**
 * Check if a given object implements the LetterConfigModel interface.
 */
export function instanceOfLetterConfigModel(value: object): value is LetterConfigModel {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('includeSignUp' in value) || value['includeSignUp'] === undefined) return false;
    if (!('includeTableOfContents' in value) || value['includeTableOfContents'] === undefined) return false;
    if (!('signUpIncludeAbroadClause' in value) || value['signUpIncludeAbroadClause'] === undefined) return false;
    if (!('includeFrontPage' in value) || value['includeFrontPage'] === undefined) return false;
    if (!('includeHolidayLawPage' in value) || value['includeHolidayLawPage'] === undefined) return false;
    if (!('place' in value) || value['place'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('organizationName' in value) || value['organizationName'] === undefined) return false;
    if (!('people' in value) || value['people'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('logo' in value) || value['logo'] === undefined) return false;
    return true;
}

export function LetterConfigModelFromJSON(json: any): LetterConfigModel {
    return LetterConfigModelFromJSONTyped(json, false);
}

export function LetterConfigModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LetterConfigModel {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'includeSignUp': json['includeSignUp'],
        'includeTableOfContents': json['includeTableOfContents'],
        'signUpIncludeAbroadClause': json['signUpIncludeAbroadClause'],
        'includeFrontPage': json['includeFrontPage'],
        'includeHolidayLawPage': json['includeHolidayLawPage'],
        'place': json['place'],
        'address': json['address'],
        'organizationName': json['organizationName'],
        'website': json['website'] == null ? undefined : json['website'],
        'people': ((json['people'] as Array<any>).map(VorstandFromJSON)),
        'bankInformation': json['bankInformation'] == null ? undefined : BankInformationFromJSON(json['bankInformation']),
        'date': (new Date(json['date'])),
        'logo': json['logo'],
    };
}

  export function LetterConfigModelToJSON(json: any): LetterConfigModel {
      return LetterConfigModelToJSONTyped(json, false);
  }

  export function LetterConfigModelToJSONTyped(value?: LetterConfigModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'includeSignUp': value['includeSignUp'],
        'includeTableOfContents': value['includeTableOfContents'],
        'signUpIncludeAbroadClause': value['signUpIncludeAbroadClause'],
        'includeFrontPage': value['includeFrontPage'],
        'includeHolidayLawPage': value['includeHolidayLawPage'],
        'place': value['place'],
        'address': value['address'],
        'organizationName': value['organizationName'],
        'website': value['website'],
        'people': ((value['people'] as Array<any>).map(VorstandToJSON)),
        'bankInformation': BankInformationToJSON(value['bankInformation']),
        'date': ((value['date']).toISOString().substring(0,10)),
        'logo': value['logo'],
    };
}

