/* tslint:disable */
/* eslint-disable */
/**
 * letter_api API
 * letter_api API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Vorstand
 */
export interface Vorstand {
    /**
     * 
     * @type {string}
     * @memberof Vorstand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Vorstand
     */
    role: VorstandRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof Vorstand
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Vorstand
     */
    phone?: string;
}


/**
 * @export
 */
export const VorstandRoleEnum = {
    Vorstand: 'Vorstand',
    Vorstaendin: 'Vorstaendin',
    Kurat: 'Kurat',
    Kuratin: 'Kuratin'
} as const;
export type VorstandRoleEnum = typeof VorstandRoleEnum[keyof typeof VorstandRoleEnum];


/**
 * Check if a given object implements the Vorstand interface.
 */
export function instanceOfVorstand(value: object): value is Vorstand {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function VorstandFromJSON(json: any): Vorstand {
    return VorstandFromJSONTyped(json, false);
}

export function VorstandFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vorstand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': json['role'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

  export function VorstandToJSON(json: any): Vorstand {
      return VorstandToJSONTyped(json, false);
  }

  export function VorstandToJSONTyped(value?: Vorstand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'role': value['role'],
        'email': value['email'],
        'phone': value['phone'],
    };
}

